FROM python:3.11-slim

WORKDIR /torcs

RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y --no-install-recommends wine wine32 tmux libgl1-mesa-dri libgl1-mesa-dri:i386 libgl1 libgl1:i386 libglu1-mesa libglu1-mesa:i386

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY launch.sh .
RUN chmod +x /torcs/launch.sh
COPY gym_torcs /torcs/gym_torcs
COPY torcs /torcs/torcs

CMD ["/torcs/launch.sh"]