FROM python:3.11-slim

WORKDIR /torcs

RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y --no-install-recommends wine wine32 tmux libgl1-mesa-dri libgl1-mesa-dri:i386 libgl1 libgl1:i386 libglu1-mesa libglu1-mesa:i386 libxkbcommon0 libegl1 libxcb1 libx11-6 libx11-xcb1 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render0 libxcb-render-util0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxext6 libxrender1 libxrandr2 libxi6 libsm6 libice6 libfontconfig1 libdbus-1-3 libxkbcommon-x11-0

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

COPY launch.sh .
COPY test.py .
RUN chmod +x /torcs/launch.sh
COPY gym_torcs /torcs/gym_torcs
COPY torcs /torcs/torcs
COPY launch_menu /torcs/launch_menu

CMD ["python3", "test.py"]